name: Build and Upload Artifact

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest  # or ubuntu-latest, macos-latest

    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-output
          path: dist/  # Replace with your actual output folder
          retention-days: 3