name: Build Electron App (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend (Vite)
        working-directory: ./frontend
        run: npm run build

      - name: Build Electron app (Windows)
        run: npm run build:win

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmployeeTracker-Windows
          path: dist-build/