name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python (for SQLite build)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-exact @journeyapps/sqlcipher@5.3.1

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Rebuild native modules
        run: |
          npm rebuild sqlite3 --runtime=electron --target=28.1.0 --disturl=https://electronjs.org/headers --abi=116
          npm rebuild @journeyapps/sqlcipher --runtime=electron --target=28.1.0 --disturl=https://electronjs.org/headers --abi=116

      - name: Build frontend
        run: npm run build

      - name: Build Windows installer
        run: npm run build:win --publish=never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmployeeTracker-Windows
          path: dist-build/*.exe