name: Build and Upload Artifact

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest, macos-latest

    permissions:
      contents: read
      actions: read

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js (example - customize as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Example build step (replace with your actual build commands)
      - name: Build project
        run: |
          npm install
          npm run build

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            build/
            *.log
          if-no-files-found: warn  # Options: error, warn, ignore
          retention-days: 5  # Optional: auto-delete after X days